### PR TITLE
feat: review Chinese trans

### PR DESCRIPTION
**Pull request by astroleander**
Reviewed all simplied Chinese translation.

### CODE REVIEW

**Comment by astroleander** [comment]
# 3782: Can I have more context what the 'Accessibility' here? is it a type of marks or for app itself's accessibility?

**Comment by astroleander** [comment]
#5926: Can I have more context about 'base_map_pin_size' meaning here?

**Comment by androidseb** [comment]
> Reviewed all simplied Chinese translation.

Thank you very much for this!

> #912: Can I have more context what the 'used' meaning here?

"Used compass sensor" means the sensors being used as a compass to orient the user's position

> #3782: Can I have more context what the 'Accessibility' here? is it a type of marks or for app itself's accessibility?

"Accessibility" is a map icon category for POI icons around accessibility POIs (e.g. wheelchair-accessible elevator)

> #5926: Can I have more context about 'base_map_pin_size' meaning here?

This is the base size of map pins on the map, it's a setting in the app - changing this will change the size of the pins from tiny, to small, to normal, to large, to huge.

**Comment by astroleander** [comment]
thanks for you replying, updated

**Comment by androidseb** [comment]
Thank you for your contribution, I'll work on getting those updated translations in the next app release.
Could you please let me know the nickname I should use to mention you in the "thank you" notes of the app?

**Pull request merged**
