### PR TITLE
Update ru_strings.md

### PR DESCRIPTION
**Pull request by fompahaha**
Much more understandable and familiar... I should check the translation in the application itself.

### CODE REVIEW

**Comment by androidseb** [comment]
Thank you for doing all this work!
Here is a modified version of the app with your translations (see attachment).
[MapMarker_TEST_RU_TRANSLATIONS.zip](https://github.com/androidseb/mapmarkerapptranslations/files/2691807/MapMarker_TEST_RU_TRANSLATIONS.zip)

**Comment by fompahaha** [comment]
oOOops I already see my mistakes. Can I send new fixes in GitHub? Such an interesting site, I like it.
________________________________
От: androidseb <notifications@github.com>
Отправлено: 18 декабря 2018 г. 21:46
Кому: androidseb/mapmarkerapptranslations
Копия: Павел Фоменко; Author
Тема: Re: [androidseb/mapmarkerapptranslations] Update ru_strings.md (#1)


Thank you for doing all this work!
Here is a modified version of the app with your translations (see attachment).
MapMarker_TEST_RU_TRANSLATIONS.zip<https://github.com/androidseb/mapmarkerapptranslations/files/2691807/MapMarker_TEST_RU_TRANSLATIONS.zip>

**Comment by androidseb** [comment]
Sure, you can send the fixes on Github. Let me know if you need assistance starting with your current progress.

**Comment by androidseb** [comment]
Thank you for the new changes!
Here is the new version:
[MapMarker_RU_TRANSLATIONS_TEST_2.zip](https://github.com/androidseb/mapmarkerapptranslations/files/2705324/MapMarker_RU_TRANSLATIONS_TEST_2.zip)

**Comment by fompahaha** [comment]
OK. I decided to commit a few more changes, now everything looks good.

________________________________
От: androidseb <notifications@github.com>
Отправлено: Saturday, December 22, 2018 6:32:55 PM
Кому: androidseb/mapmarkerapptranslations
Копия: Павел Фоменко; Author
Тема: Re: [androidseb/mapmarkerapptranslations] Update ru_strings.md (#1)


Thank you for the new changes!
Here is the new version:
MapMarker_RU_TRANSLATIONS_TEST_2.zip<https://github.com/androidseb/mapmarkerapptranslations/files/2705324/MapMarker_RU_TRANSLATIONS_TEST_2.zip>

**Comment by androidseb** [comment]
Ok, thank you very much. I will merge the changes now.
The updated translations will be available in the next beta version (soon).
The public app update will be later, probably some time in January.

**Pull request merged**
